### ISSUE TITLE
Comments are red after last VS Code update

### ISSUE THREAD

**Issue by TheDutchCoder** [Binaryify/Material-Theme-vscode#14]
After the last updates, all comments have turned red 😞 

![image](https://cloud.githubusercontent.com/assets/1668207/23487491/7d24b242-feb4-11e6-9164-2e83a861e799.png)

**Comment by weareoutman** [comment]
😞 +1

**Comment by leozdgao** [comment]
😞  +1

**Comment by jayden2** [comment]
😞 +1

**Comment by acmilank22** [comment]
😞 +1

**Comment by Binaryify** [comment]
I fixed it,sorry

**Comment by jayden2** [comment]
tough working conditions @Binaryify
👍 thank you!

**Comment by tz5514** [comment]
thanks for fixing!
