### ISSUE TITLE
Does not support Linux?

### ISSUE THREAD

**Issue by QiuMing** [Binaryify/Material-Theme-vscode#15]
It did not work in linux minit and ubuntu.

**Comment by Binaryify** [comment]
Can you provide a screenshot?

**Comment by QiuMing** [comment]
![2017-03-06 10-03-56](https://cloud.githubusercontent.com/assets/11348698/23594419/deeee058-0254-11e7-986d-7b44b33dd1db.png)

**Comment by Binaryify** [comment]
Does you apply this theme?
![image](https://cloud.githubusercontent.com/assets/12221718/23594476/4b3076d2-0255-11e7-8c2d-7808acbb5347.png)

![image](https://cloud.githubusercontent.com/assets/12221718/23594470/4414f8f0-0255-11e7-8310-15f27df7e81b.png)

**Comment by QiuMing** [comment]
恩恩，可以了，多谢
