### ISSUE TITLE
Material-Theme is an awesome work,but the code annotation color was so light

### ISSUE THREAD

**Issue by jasonChen1982** [Binaryify/Material-Theme-vscode#17]
![image](https://cloud.githubusercontent.com/assets/8683772/23733980/fc3fb646-04b6-11e7-8573-7960c5a7f838.png)

**Comment by jasonChen1982** [comment]
in vscode 1.10.1

**Comment by Binaryify** [comment]
@jasonChen1982 
What theme version
What language

**Comment by Binaryify** [comment]
@jasonChen1982 
visit it https://github.com/Binaryify/Material-Theme-vscode/issues/14
