### ISSUE TITLE
Javascript 'this' key word is not high light

### ISSUE THREAD

**Issue by CrisLi** [Binaryify/Material-Theme-vscode#19]
OSX 10.11.16
Material-Theme 2.2.5

The `this` key word is not high light in the **javascript** or **jsx** language mode.

**Comment by Binaryify** [comment]
Can you provide screenshot? thx~

**Comment by CrisLi** [comment]
<img width="381" alt="screen" src="https://cloud.githubusercontent.com/assets/360767/23990768/0889ad10-0a72-11e7-8ce6-30ce31990bdb.png">

As you can see, the `this` is same color with other statements.

Beside, it is good to make `module` and `exports` hight light.

**Comment by Binaryify** [comment]
@CrisLi
I got it, will improve it when I come home, thx~

**Comment by Binaryify** [comment]
@CrisLi  I improve it, please update, and see if it look like what you want, thx~

**Comment by CrisLi** [comment]
@Binaryify fantastic!

It looks good.

Is that possible make `module` and `exports` highlight too? These are keywords in the Node platform.

**Comment by Binaryify** [comment]
@CrisLi 
You mean make `module ` and `exports ` have the same color with the `this`?

**Comment by CrisLi** [comment]
@Binaryify 
Yes, that what I mean. Do you think is okay?

**Comment by Binaryify** [comment]
@CrisLi 
I think it's a good idea, and I had changed it, please update!
