### ISSUE TITLE
css highlighting all wonky

### ISSUE THREAD

**Issue by Sartan4455** [Binaryify/Material-Theme-vscode#20]
Many of the attributes will not highlight correctly...notice float: left
and margin: 100px auto 0 auto

![material-css](https://cloud.githubusercontent.com/assets/1134294/24017164/8a19e08e-0a54-11e7-9316-9b42cca597ce.png)

**Comment by Sartan4455** [comment]
Ah, I should note this is an scss file...

**Comment by Binaryify** [comment]
@Sartan4455 
I fix it, please update, thx~

**Comment by Sartan4455** [comment]
Looks fixed!  Thanks for the quick turn around.  I like the theme!

**Comment by Binaryify** [comment]
@Sartan4455
 thank you ~
