### ISSUE TITLE
Requesting Python Syntax Highlighting improvement

### ISSUE THREAD

**Issue by LordAmit** [Binaryify/Material-Theme-vscode#23]
![image](https://cloud.githubusercontent.com/assets/480479/24787118/404c1c98-1b88-11e7-844f-2391832fd459.png)

I think it is self-explanatory. Color of method name and parameter should not be same. 

Hope you will take a look at it. :smile: Thank you for the awesome theme!

**Comment by Binaryify** [comment]
@LordAmit 
I will fix it soon

**Comment by LordAmit** [comment]
Glad to know :) 
I have already noticed the frequent updates from you. Please do take care of yourself.

**Comment by Binaryify** [comment]
I fix it , however the  parameter scope is same to the comma scope, so I remove parameter height light, please update and check it, thx~

**Comment by LordAmit** [comment]
Hi,

It looks like this now:

![image](https://cloud.githubusercontent.com/assets/480479/24788771/1d09588c-1b91-11e7-8cce-b3123ef849fa.png)

I was imagining that the objects will be red, similar to the screenshot from your demo.js; but this will do. :smile:

**Comment by Binaryify** [comment]
@LordAmit 
I also want it be red, but it will affect comma cause it have same scope to  the comma scope, I hope VS Code will improve it
