### ISSUE TITLE
Python - Boolean operator Keywords are not being highlighted

### ISSUE THREAD

**Issue by LordAmit** [Binaryify/Material-Theme-vscode#25]
Hi,
The boolean related keywords, such as `and`, `or`, `not` are not being highlighted properly in Python.
Here is a sample screenshot.
![image](https://cloud.githubusercontent.com/assets/480479/24800839/a442f2f4-1bc3-11e7-970b-35c49fe07285.png)
Thanks again for your support! :smile:

**Comment by Binaryify** [comment]
I improve it, please update and check it, thx~

**Comment by LordAmit** [comment]
Thanks! Closing this. :smile:
