### ISSUE TITLE
Python - Highlight standard types / Default types

### ISSUE THREAD

**Issue by LordAmit** [Binaryify/Material-Theme-vscode#26]
Hi,
There are some default types in Python, such as `int`, `float`, `List` etc. More details are available here: 
https://docs.python.org/3/library/stdtypes.html

The theme is not currently highlighting these standard types as separate words. 
Can you please check? 
TIA!

**Comment by Binaryify** [comment]
Can you  provide some code? Thx~

**Comment by LordAmit** [comment]
Of course!

![image](https://cloud.githubusercontent.com/assets/480479/24827526/73190268-1c6d-11e7-8307-8b23dd808b1d.png)

**Comment by LordAmit** [comment]
Do not mind the green squiggly line btw. It is due to PyLint giving variable name convention.

**Comment by Binaryify** [comment]
@LordAmit 
Now it support, please update and check it

**Comment by LordAmit** [comment]
Nice! But should not this be a bit more different from the method/function colors? Looks almost same!

**Comment by Binaryify** [comment]
@LordAmit 
Yup, I consider it

**Comment by Binaryify** [comment]
@LordAmit 
How about now?

**Comment by LordAmit** [comment]
To be honest, colors like ocean green and ocean blue are really close when it comes to dim background. 
Check the str and adb_list_avd_devices() for example.
![image](https://cloud.githubusercontent.com/assets/480479/24828713/f3648c1e-1c84-11e7-9a2d-c4fe9392f7dc.png)

**Comment by Binaryify** [comment]
@LordAmit 
I will write a docs about how to change the theme color, you can design it by yourself

**Comment by LordAmit** [comment]
Thanks!

**Comment by Binaryify** [comment]
@LordAmit 
Here the docs
[https://binaryify.github.io/Material-Theme-vscode/#/](https://binaryify.github.io/Material-Theme-vscode/#/)
