### ISSUE TITLE
php misstyled

### ISSUE THREAD

**Issue by jens1o** [Binaryify/Material-Theme-vscode#28]
Hi!

`use AdvancedJsonRpc\{Request as RequestBody, Response as ResponseBody};`

gets 
![image](https://cloud.githubusercontent.com/assets/11234139/24839942/c354fa10-1d63-11e7-934f-46e391f25e5e.png)

I expect the second as to be in the same color of  the first.

other thing:
![image](https://cloud.githubusercontent.com/assets/11234139/24839948/f63e6d3a-1d63-11e7-9d1a-6274b17c2d79.png)
I expect that `array` is as yellow as `string`. You probably got worried by the array constructor `array()`
```php
public function __construct(string $uri = null, array $range = null)
    {
        $this->uri = $uri;
        $this->range = $range;
    }
```

**Comment by Binaryify** [comment]
@jens1o 
I fix it, and here the docs about how to design this theme
[https://binaryify.github.io/Material-Theme-vscode/#/?id=contribute](https://binaryify.github.io/Material-Theme-vscode/#/?id=contribute)

**Comment by jens1o** [comment]
Thanks. Okey, so in the future I can do prs and fix it myself for all users?

**Comment by Binaryify** [comment]
@jens1o 
Of course !
