### ISSUE TITLE
Whitespace & indent guide colors

### ISSUE THREAD

**Issue by hkan** [Binaryify/Material-Theme-vscode#33]
This isn't really an issue but I'm just wondering, and since I'm using this theme I thought it'd be the right place to ask it. I looked around a bit to find out which setting changes whitespaces' and indent guides' colors but had no luck. Where should I edit to change the color of those vertical lines and dots in the screenshot?

![screen shot 2017-04-11 at 19 13 40](https://cloud.githubusercontent.com/assets/2135597/24920104/a4f84766-1eee-11e7-8fcf-56af4aa3be21.png)

**Comment by Binaryify** [comment]
@hkan 
Preferences > Settings
```
"editor.renderWhitespace": "none",
 "editor.renderIndentGuides": false
```

**Comment by hkan** [comment]
I don't want to disable them. I just want to change their colors.

**Comment by Binaryify** [comment]
@hkan 
Oh, I misunderstand your mean

**Comment by Binaryify** [comment]
@hkan 
Material-Theme.tmTheme file
```xml
<key>invisibles</key>
<string>#4b525b</string>
```
You can watch this document [https://binaryify.github.io/Material-Theme-vscode/#/?id=design](https://binaryify.github.io/Material-Theme-vscode/#/?id=design)

**Comment by hkan** [comment]
I'm pretty sure that I tried that one and it didn't change anything, but now it works. Thanks!
