### ISSUE TITLE
Update frequency

### ISSUE THREAD

**Issue by alexlur** [Binaryify/Material-Theme-vscode#35]
Is there any particular reason that this extension gets update so frequently? Visual Studio Code tells me there is an update almost daily.

**Comment by Binaryify** [comment]
Recently it not frequency ! Now updated once almost three days
 In 2017.4.10, I updata too much.

**Comment by Binaryify** [comment]
And when developer send a PR, I will merge it and update, please understanding it, now it stable, will not update long time

**Comment by alexlur** [comment]
Thanks for the quick response!

**Comment by Binaryify** [comment]
You can watch the PR list, https://github.com/Binaryify/Material-Theme-vscode/pulls?q=is%3Apr+is%3Aclosed  , about php PR has 5  recently
