### ISSUE TITLE
Very Low Contrast in comments in compare view (source control)

### ISSUE THREAD

**Issue by tolu** [Binaryify/Material-Theme-vscode#38]
First of all, thanks for an amazing theme!

I'd love to see if it were possible to get a better contrast for diff's in comments.

Here with javascript
![image](https://cloud.githubusercontent.com/assets/658586/25303715/ea6edd6a-2758-11e7-9a24-6647def03a5d.png)

And this is C#
![image](https://cloud.githubusercontent.com/assets/658586/25303823/e451f1b8-275a-11e7-9881-693fd358c319.png)

Comments might not be the most important thing in a compare view but it should at least be possible to see the changes at all 😄

**Comment by Binaryify** [comment]
Sorry about it, but the comments background color can't change, you can change the theme background  
Add this code snippet in your 'settings.json' file
```
"workbench.experimental.colorCustomizations":{
    "activeTabBackground": "#282c34",
    "activityBarBackground":"#282c34",
    "editorGroupBackground": "#282c34",
    "sideBarBackground": "#282c34",
    "editorBackground": "the background color you want"
  }
```

**Comment by tolu** [comment]
thanks for the quick response and the tip!

**Comment by Binaryify** [comment]
@tolu 
You can see this issue https://github.com/Binaryify/OneDark-Pro/issues/52#issuecomment-300348666

**Comment by tolu** [comment]
Fantastic, you made my day, thanks @binaryify!!!

**Comment by Binaryify** [comment]
@tolu 
The new feature will come next version, but you can edit the 'setting.json' before the update come
