### ISSUE TITLE
C++ ordinary code color become rose red

### ISSUE THREAD

**Issue by f3wenbo** [Binaryify/Material-Theme-vscode#39]
![ws000036](https://cloud.githubusercontent.com/assets/10846537/25320088/db4bf1ba-28de-11e7-99bc-ef98aa8f9785.JPG)
C++ ordinary code color become rose red

**Comment by Binaryify** [comment]
Can you provide the code text ?

**Comment by f3wenbo** [comment]
`enum OPERATION_TYPE
{
	TYPE_UNKNOWN								= 0,
	TYPE_JOB_CONFIG_CREATE						= 1,
	TYPE_JOB_CONFIG_DELETE						= 2,
	TYPE_JOB_CONFIG_CURRENT_SET					= 3,
	TYPE_JOB_CONFIG_CURRENT_GET					= 4,
	TYPE_JOB_CONFIG_DEFAULT_GET					= 5,
	TYPE_JOB_CONFIG_SEND_DESTINATION_REGISTER	= 6,
	TYPE_JOB_CONFIG_SEND_DESTINATION_UPDATE		= 7,
	TYPE_JOB_CONFIG_SEND_DESTINATION_GET		= 8,
	TYPE_JOB_CONFIG_LIST_GET					　　= 9,
	TYPE_JOB_CONFIG_SEND_DESTINATION_DELETE		= 10,
	TYPE_JOB_CONFIG_DUPLICATION_CHECK			= 11,
	TYPE_JOB_CONFIG_DETAIL_SETTING_START		　　= 12,
	TYPE_JOB_CONFIG_DETAIL_SETTING_OK			= 13,
};`
Here is the code text. I only wrote a sample head file.

**Comment by Binaryify** [comment]
I fix it

**Comment by f3wenbo** [comment]
Thank you!! I like this theme so much.
