### ISSUE TITLE
One screenshot of the theme in the readme... can do wonders

### ISSUE THREAD

**Issue by Narven** [Binaryify/Material-Theme-vscode#4]
One screenshot of the theme in the readme... can do wonders

**Comment by RWOverdijk** [comment]
👍

**Comment by george3447** [comment]
+1

**Comment by Beatusvir** [comment]
Came here to open this **_issue_**

**Comment by corysimmons** [comment]
0. push button to install theme
0. activate it
0. look at it
0. push button to uninstall theme if you don't like it

![image](https://cloud.githubusercontent.com/assets/224636/20017741/46f423c6-a29b-11e6-95fb-68a9f84bb367.png)

I'm just kidding, I feel you guys.

**Comment by Narven** [comment]
@corysimmons why are u putting the screenshot here?

If someone what's to take a look at it, has to find this *issue* and look at it?

Put it on the README.md, and it would be available for any person in the world to look either from coming directly into here and on the marketplace, AND ALSO like you mention, BEFORE push to install theme... they can see it right away directly from VSC.

Simple, easy.

**Comment by corysimmons** [comment]
Why don't you? You have the screenshot now. I've done all the hard work!
