### ISSUE TITLE
请问有旧版本的配色下载吗？

### ISSUE THREAD

**Issue by DMQ** [Binaryify/Material-Theme-vscode#9]
不小心更新了新版插件，很不习惯新的配色呀，还是喜欢以前简洁的配色。

**Comment by Binaryify** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">

<plist version="2.4">
<dict>
  <key>author</key>
  <string>Mattia Astorino (http:&#x2f;&#x2f;astorinomattia.it)</string>
  <key>name</key>
  <string>Material Theme</string>
  <key>semanticClass</key>
  <string>theme.dark.material_theme</string>
  <key>colorSpaceName</key>
  <string>sRGB</string>
  <key>settings</key>
  <array>
    <dict>
      <key>settings</key>
      <dict>
        <key>background</key>
        <string>#263238</string>    
        <key>caret</key>
        <string>#c0c5ce</string>
        <key>foreground</key>
        <string>#80CBC470</string>
        <key>invisibles</key>
        <string>#65737e</string>
        <key>lineHighlight</key>
        <string>#00000030</string>
        <key>selection</key>
        <string>#80CBC420</string>
        <key>guide</key>
        <string>#37474F80</string>
        <key>activeGuide</key>
        <string>#80CBC470</string>
        <key>stackGuide</key>
        <string>#37474Fff</string>
        <key>gutterForeground</key>
        <string>#37474F</string>
        <key>findHighlight</key>
        <string>#F8E71C</string>
        <key>shadow</key>
        <string>#00000010</string>          
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Text</string>
      <key>scope</key>
      <string>variable.parameter.function</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#eeffffff</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Comments</string>
      <key>scope</key>
      <string>comment, punctuation.definition.comment</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#546E7A</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Text and Source Base Colors</string>
      <key>scope</key>
      <string>text, source</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#CDD3DE</string> 
      </dict>
    </dict>   
    <dict>
      <key>name</key>
      <string>Punctuation</string>
      <key>scope</key>
      <string>punctuation.definition.string, punctuation.definition.variable, punctuation.definition.string, punctuation.definition.parameters, punctuation.definition.string, punctuation.definition.array</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#d9f5dd</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Delimiters</string>
      <key>scope</key>
      <string>none</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#d9f5ddff</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Operators</string>
      <key>scope</key>
      <string>keyword.operator</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#d9f5ddff</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Keywords</string>
      <key>scope</key>
      <string>keyword</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#c792eaff</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Variables</string>
      <key>scope</key>
      <string>variable</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#eeffff</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Functions</string>
      <key>scope</key>
      <string>entity.name.function, meta.require, support.function.any-method,
meta.function-call, support.function, keyword.other.special-method, meta.block-level</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#82B1FF</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Classes</string>
      <key>scope</key>
      <string>support.class, entity.name.class, entity.name.type.class</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#ffcb6b</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Classes</string>
      <key>scope</key>
      <string>meta.class</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#ffffff</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Methods</string>
      <key>scope</key>
      <string>keyword.other.special-method</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#82B1FF</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Storage</string>
      <key>scope</key>
      <string>storage</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#c792eaff</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Support</string>
      <key>scope</key>
      <string>support.function,
keyword.operator, constant.other.color, meta.tag, punctuation.definition.tag, punctuation.separator.inheritance.php, punctuation.definition.tag.html, punctuation.definition.tag.begin.html, punctuation.definition.tag.end.html, meta.function-call meta.function-call.arguments variable.parameter.function, text.html.markdown meta.paragraph meta.link.inline, text.html.markdown meta.paragraph meta.link.inline punctuation.definition.string.begin.markdown, text.html.markdown meta.paragraph meta.link.inline punctuation.definition.string.end.markdown</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#80CBC4</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Strings, Inherited Class</string>
      <key>scope</key>
      <string>string, constant.other.symbol, entity.other.inherited-class</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#C3E88D</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Integers</string>
      <key>scope</key>
      <string>constant.numeric</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#F77669</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Floats</string>
      <key>scope</key>
      <string>none</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#F77669</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Boolean</string>
      <key>scope</key>
      <string>none</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#F77669</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Constants</string>
      <key>scope</key>
      <string>constant</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#F77669</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Tags</string>
      <key>scope</key>
      <string>entity.name.tag</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#ff5370ff</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Attributes</string>
      <key>scope</key>
      <string>entity.other.attribute-name</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#FFCB6B</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Attribute IDs</string>
      <key>scope</key>
      <string>entity.other.attribute-name.id</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#FAD430</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Selector</string>
      <key>scope</key>
      <string>meta.selector</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#c792eaff</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Values</string>
      <key>scope</key>
      <string>none</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#F77669</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Headings</string>
      <key>scope</key>
      <string>markup.heading punctuation.definition.heading, entity.name.section</string>
      <key>settings</key>
      <dict>
        <key>fontStyle</key>
        <string></string>
        <key>foreground</key>
        <string>#78ccf0ff</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Units</string>
      <key>scope</key>
      <string>keyword.other.unit</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#F77669</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Bold</string>
      <key>scope</key>
      <string>markup.bold, punctuation.definition.bold</string>
      <key>settings</key>
      <dict>
        <key>fontStyle</key>
        <string>bold</string>
        <key>foreground</key>
        <string>#ffcb6b</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Italic</string>
      <key>scope</key>
      <string>markup.italic, punctuation.definition.italic</string>
      <key>settings</key>
      <dict>
        <key>fontStyle</key>
        <string>italic</string>
        <key>foreground</key>
        <string>#c792eaff</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Code</string>
      <key>scope</key>
      <string>markup.raw.inline</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#f1e655</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Link Text</string>
      <key>scope</key>
      <string>string.other.link, punctuation.definition.string.end.markdown</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#ff5370</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Link Url</string>
      <key>scope</key>
      <string>meta.link</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#F77669</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Lists</string>
      <key>scope</key>
      <string>markup.list</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#ff5370ff</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Quotes</string>
      <key>scope</key>
      <string>markup.quote</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#F77669</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Separator</string>
      <key>scope</key>
      <string>meta.separator</string>
      <key>settings</key>
      <dict>
        <key>background</key>
        <string>#1e3445ff</string>
        <key>foreground</key>
        <string>#d9f5ddff</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Inserted</string>
      <key>scope</key>
      <string>markup.inserted</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#F1E655</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Deleted</string>
      <key>scope</key>
      <string>markup.deleted</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#ff5370ff</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Changed</string>
      <key>scope</key>
      <string>markup.changed</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#c792eaff</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Colors</string>
      <key>scope</key>
      <string>constant.other.color,
meta.property-value support.constant.named-color.css</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#FFEB95</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Regular Expressions</string>
      <key>scope</key>
      <string>string.regexp</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#80CBC4</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Escape Characters</string>
      <key>scope</key>
      <string>constant.character.escape</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#80CBC4</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Embedded</string>
      <key>scope</key>
      <string>punctuation.section.embedded, variable.interpolation</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#d3423eff</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Illegal</string>
      <key>scope</key>
      <string>invalid.illegal</string>
      <key>settings</key>
      <dict>
        <key>background</key>
        <string>#EC5F67</string>
        <key>foreground</key>
        <string>#ffffffff</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Broken</string>
      <key>scope</key>
      <string>invalid.broken</string>
      <key>settings</key>
      <dict>
        <key>background</key>
        <string>#F77669</string>
        <key>foreground</key>
        <string>#020e14ff</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Deprecated</string>
      <key>scope</key>
      <string>invalid.deprecated</string>
      <key>settings</key>
      <dict>
        <key>background</key>
        <string>#d3423eff</string>
        <key>foreground</key>
        <string>#ffffffff</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Unimplemented</string>
      <key>scope</key>
      <string>invalid.unimplemented</string>
      <key>settings</key>
      <dict>
        <key>background</key>
        <string>#8BD649</string>
        <key>foreground</key>
        <string>#ffffffff</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>SublimeLinter Annotations</string>
      <key>scope</key>
      <string>sublimelinter.annotations</string>
      <key>settings</key>
      <dict>
        <key>background</key>
        <string>#fffff7ff</string>
        <key>foreground</key>
        <string>#7b5157ff</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>SublimeLinter Error Outline</string>
      <key>scope</key>
      <string>sublimelinter.outline.illegal</string>
      <key>settings</key>
      <dict>
        <key>background</key>
        <string>#ff9599ff</string>
        <key>foreground</key>
        <string>#ffffffff</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>SublimeLinter Error Underline</string>
      <key>scope</key>
      <string>sublimelinter.underline.illegal</string>
      <key>settings</key>
      <dict>
        <key>background</key>
        <string>#ff4941ff</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>SublimeLinter Warning Outline</string>
      <key>scope</key>
      <string>sublimelinter.outline.warning</string>
      <key>settings</key>
      <dict>
        <key>background</key>
        <string>#FFCF1B</string>
        <key>foreground</key>
        <string>#ffffffff</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>SublimeLinter Warning Underline</string>
      <key>scope</key>
      <string>sublimelinter.underline.warning</string>
      <key>settings</key>
      <dict>
        <key>background</key>
        <string>#ff4941ff</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>SublimeLinter Violation Outline</string>
      <key>scope</key>
      <string>sublimelinter.outline.violation</string>
      <key>settings</key>
      <dict>
        <key>background</key>
        <string>#ffffff33</string>
        <key>foreground</key>
        <string>#ffffffff</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>SublimeLinter Violation Underline</string>
      <key>scope</key>
      <string>sublimelinter.underline.violation</string>
      <key>settings</key>
      <dict>
        <key>background</key>
        <string>#ff4941ff</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>SublimeLinter Error</string>
      <key>scope</key>
      <string>sublimelinter.mark.error</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#ff572dff</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>SublimeLinter Warning</string>
      <key>scope</key>
      <string>sublimelinter.mark.warning</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#ffcf1bff</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>SublimeLinter Gutter Mark</string>
      <key>scope</key>
      <string>sublimelinter.gutter-mark</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#ffffffff</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>GitGutter deleted</string>
      <key>scope</key>
      <string>markup.deleted.git_gutter</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#EC5F67</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>GitGutter changed</string>
      <key>scope</key>
      <string>markup.changed.git_gutter</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#FFCF1B</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>GitGutter inserted</string>
      <key>scope</key>
      <string>markup.inserted.git_gutter</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#C3E88D</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>GitGutter Ignored</string>
      <key>scope</key>
      <string>markup.ignored.git_gutter</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#546E7A</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Comment line &#x2f;&#x2f;</string>
      <key>scope</key>
      <string>comment.line.double-slash punctuation.definition.comment, meta.structure.array comment.block.json punctuation.definition.comment</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#5C7E8C</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Result file path</string>
      <key>scope</key>
      <string>text.find-in-files entity.name.filename.find-in-files</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#FFEB95</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>CSS: Property-name</string>
      <key>scope</key>
      <string>support.type.property-name</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#80CBC4</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>CSS: Prefix</string>
      <key>scope</key>
      <string>meta.property-list meta.property-name</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#80CBC4</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Styles Units</string>
      <key>scope</key>
      <string>source.css keyword.other.unit,
source.less keyword.other.unit,
source.scss keyword.other.unit,
source.sass keyword.other.unit</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#FFEB95</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>LESS: mixins</string>
      <key>scope</key>
      <string>entity.other.less.mixin</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#7986CB</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>CSS: #</string>
      <key>scope</key>
      <string>constant.other.color.rgb-value punctuation.definition.constant</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#F77669</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>CSS: Attribute selector value</string>
      <key>scope</key>
      <string>meta.attribute-selector string.unquoted.attribute-value</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#C3E88D</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>CSS: Attribute selector name</string>
      <key>scope</key>
      <string>meta.attribute-selector entity.other.attribute-name.attribute</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#F77669</string>
      </dict>
    </dict>
    
    <dict>
      <key>name</key>
      <string>This</string>
      <key>scope</key>
      <string>variable.language.this.js, variable.language.arguments.js, variable.language.super.js, variable.language.proto.js, variable.language.constructor.js, variable.language.prototype.js</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#ff6380</string>
      </dict>
    </dict>
    
    <dict>
      <key>name</key>
      <string>keyword.operator.module.js</string>
      <key>scope</key>
      <string>keyword.operator.module.js</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#c792eaff</string>
      </dict>
    </dict>
    
    <dict>
      <key>name</key>
      <string>entity.name.method.js</string>
      <key>scope</key>
      <string>entity.name.method.js</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#82B1FF</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>entity.name.accessor.js</string>
      <key>scope</key>
      <string>entity.name.accessor.js</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>#82B1FF</string>
      </dict>
    </dict>
  </array>
  <key>uuid</key>
  <string>133d1250-19c6-4565-bc93-b37fd36f7fc9</string>
</dict>
</plist>

**Comment by Binaryify** [comment]
@DMQ https://1drv.ms/u/s!AlUuk77q30Z3hegV0Ob3oculJC958w
